version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: lead_magnet_db_prod
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # Cambiar en el servidor para producción si es necesario
      POSTGRES_DB: lead_magnet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lead_magnet_backend_prod
    restart: always
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/lead_magnet_db
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=6yEM0adbFfcllTFZeJVI
      - MINIO_SECRET_KEY=oZUCk8cMAxGLLLrBuZaEVliTrNqN6YwJgMKXddLp
      - MINIO_SECURE=False
      - MINIO_EXTERNAL_ENDPOINT=files.espalhar.shop
      - MINIO_BUCKET_NAME=logicakids
      - FRONTEND_URL=https://landingopcion.espalhar.shop
      - RESEND_API_KEY=${RESEND_API_KEY}
    depends_on:
      - db
    networks:
      - default
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      # Enrutar la API en /api del host
      - "traefik.http.routers.mente-en-calma-backend.rule=Host(`landingopcion.espalhar.shop`) && PathPrefix(`/api`)"
      - "traefik.http.routers.mente-en-calma-backend.entrypoints=websecure"
      - "traefik.http.routers.mente-en-calma-backend.tls=true"
      - "traefik.http.routers.mente-en-calma-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.mente-en-calma-backend.loadbalancer.server.port=8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lead_magnet_frontend_prod
    restart: always
    depends_on:
      - backend
    networks:
      - default
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      # Enrutar el Frontend en la raíz del host
      - "traefik.http.routers.mente-en-calma-frontend.rule=Host(`landingopcion.espalhar.shop`)"
      - "traefik.http.routers.mente-en-calma-frontend.entrypoints=websecure"
      - "traefik.http.routers.mente-en-calma-frontend.tls=true"
      - "traefik.http.routers.mente-en-calma-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.mente-en-calma-frontend.loadbalancer.server.port=3080"

networks:
  traefik_proxy:
    external: true
    name: traefik_proxy

volumes:
  postgres_data:

